import "@/styles/globals.css";
  import type { Metadata } from 'next';
interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Sample",
};

function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="ja">
      <body className="">{props.children}</body>
    </html>
  );
};

export default RootLayout;
