import "@/styles/globals.css";

import type { RootLayoutProps } from "@/app/lib/interfaces/layout";
import type { Metadata } from "next";
import { getNavigationUserByUserId } from "@/app/api/profile/route";
import { FabCreate } from "@/app/ui/fab-create-post";
import Navigation from "@/app/ui/navigation";
import { auth } from "@/auth";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    description: "Generated by create next app", // TODO: ここを調整
    title: "だてまき",
};

async function RootLayout(props: RootLayoutProps) {
    const session = await auth();
    const currentUser = session?.user?.id
        ? await getNavigationUserByUserId(session.user.id)
        : null;
    const navigationUser =
        currentUser ??
        (session?.user?.id && session.user.name
            ? {
                  avatar: null,
                  id: session.user.id,
                  name: session.user.name,
              }
            : null);

    return (
        <html lang="ja">
            <body>
                <div className="flex min-h-screen flex-col bg-white">
                    <Navigation currentUser={navigationUser} />
                    <main className="container mx-auto flex flex-1 flex-col px-4 py-8">
                        <Toaster position="top-right" richColors />
                        {props.children}
                        <FabCreate />
                    </main>
                    <footer className="border-2 p-4">
                        <div className="container mx-auto text-center">
                            &copy; 2026 だてまき. All rights reserved.
                        </div>
                    </footer>
                </div>
            </body>
        </html>
    );
}

export default RootLayout;
